name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  quality:
    uses: starchaser-framework/.github/.github/workflows/js-quality.yml@dbe7d7a07f68aa0d7959823c34c0f8c30f78d867
