name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  quality:
    uses: starchaser-framework/.github/.github/workflows/js-quality.yml@8db09a07c4710f3e9768950537f34b0dd4583e8b
