name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  quality:
    uses: starchaser-framework/.github/.github/workflows/js-quality.yml@973833d8bbb15edff1612e0cb45d11119623bcbe
